apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rag 
  janus-idp.io/tekton: rag
  backstage.io/kubernetes-id: rag
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: rag
resources: 
- application-dev.yaml